name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build
        run: bundle exec jekyll build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site  # Jekyll's default build output directory
          branch: gh-pages 